# Generated by Django 4.1.3 on 2023-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(null=True, upload_to='', verbose_name='home/post/products/'),
        ),
    ]
