# Generated by Django 4.1.3 on 2023-04-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravand', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ravand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ravand',
            name='routin',
        ),
        migrations.CreateModel(
            name='imagesRavand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='home/ravand/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ravand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravand.ravand')),
            ],
        ),
    ]
