# Generated by Django 4.1.3 on 2023-02-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_food_oprator'),
        ('program', '0004_remove_sports_program_program_diet_delete_diet_and_more'),
    ]

    operations = [
    ]
