# Generated by Django 4.1.3 on 2023-05-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_pin'),
        ('reserve', '0002_alter_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='description',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
