# Generated by Django 4.1.3 on 2023-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='chatReply',
        ),
    ]
