# Generated by Django 4.1.3 on 2023-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_status_delete_chatreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=6),
        ),
    ]
