# Generated by Django 4.1.3 on 2023-04-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='', verbose_name='home/analyze/')),
                ('image2', models.ImageField(null=True, upload_to='', verbose_name='home/analyze/')),
                ('image3', models.ImageField(null=True, upload_to='', verbose_name='home/analyze/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
