# Generated by Django 4.1.3 on 2023-08-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0007_rename_descriptions_cortex_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortex',
            name='numbermeet',
        ),
    ]
