# Generated by Django 4.1.3 on 2023-08-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0008_remove_cortex_numbermeet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cortext_district',
            new_name='cortex_district',
        ),
        migrations.RenameField(
            model_name='cortex_district',
            old_name='cortext',
            new_name='cortex',
        ),
    ]
