# Generated by Django 4.1.3 on 2023-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
