# Generated by Django 4.1.3 on 2023-03-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet'),
        ('manager', '0004_manager_image_alter_manager_types'),
        ('comment', '0002_comment_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('accepted', models.BooleanField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
